### ISSUE TITLE
Can we simplify the invocation of the module?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/redis-connection#12]
at present the usage is:
```js
var redisClient = require('redis-connection')(); // invoke to start client
```
@rjmk can this be simplified such that the invocation is *automatic*?
e.g:
```js
var redisClient = require('redis-connection'); // already active client
```

**Comment by rjmk** [comment]
I'm on clear on the proposed usage. Is the idea
* start a connection 
```js
var redisClient = require('redis-connection')();
```
* grab existing connection
```js
var redisClient = require('redis-connection')
```
* grab specific connection
```js
var redisClient = require('redis-connection')(SPECIFIC_CONNECTION_NAME)
```
?

Or even that starting a connection only requires invocation if you want to name it? I can think of a way that might work to do that, but it would make it harder to understand the code of the module itself, for what I'm not sure is much of a gain in the API.

On the other hand, this might be a failure of imagination on my part.

**Comment by nelsonic** [comment]
The purpose of the invocation *was* so that we could differentiate connections
```js
var redisClient = require('redis-connection')();                // standard / publisher
var redisSub = require('redis-connection')('subscriber') // subscriber connection
```
There might not be an *elegant* way of returning a *standard* connection when the module is required *without* invocation...
But if anyone can see a *simpler* way of doing things its *you*... :wink:
thanks for taking a look at it. :+1:

**Comment by nelsonic** [comment]
Closing this for now. If someone finds a better way, we'll gladly accept a PR. :+1:
