### ISSUE TITLE
How to use redis-connection with env2?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/redis-connection#13]
The documentation on this part is not very explicit and it's not obvious that you need to name your environment variable REDISCLOUD_URL. It will be nice to have a more detailed example. Also I'm not sure about the name REDISCLOUD_URL, I prefer a more general name like REDIS_URL, other suggestions?

**Comment by nelsonic** [comment]
Good question @SimonLab, yes the documentation *should* be improved.
I *often forget* that people using this might not read [**learn-redis**](https://github.com/dwyl/learn-redis#which-redis-as-a-service-heroku-addon) where there is a *section* discussion why we are using RedisCloud: https://github.com/dwyl/learn-redis#which-redis-as-a-service-heroku-addon
We should *definitely* improve the docs for this module... do you have time...?

**Comment by SimonLab** [comment]
RedisCloud is a good addons. There is now also Heroku Redis which also have a free plan for 25mb and which seems to be the official addons for Redis on Heroku and that's why some people might prefer to use it for their projects. @nelsonic I will be happy to update the documentation on redis-connection with env2!

**Comment by nelsonic** [comment]
Yes, its *interesting* that Heroku are *directly competing* with their *established* addon providers... however https://elements.heroku.com/addons/heroku-redis  only gives 25Mb whereas https://elements.heroku.com/addons/rediscloud is 30mb for free...
but... agree 100% we need to support more providers and be *explicit* about how to use each one in the README...

**Comment by iteles** [comment]
I'm not sure it's _worth_ creating a **breaking change** (renaming of `REDISCLOUD_URL`) here. I would argue that for now it makes more sense to just alter the documentation (readme) to make this clearer until there is an actual _need_ to rename it?

**Comment by SimonLab** [comment]
@iteles it's true that it will break some code ( sorry I didn't see that). I let you decide what is the best for now.

**Comment by nelsonic** [comment]
@SimonLab let us know if you still want our input on this...?

**Comment by SimonLab** [comment]
Oups, I forget I have to work on this. I will try to close the PR link to this issue soon!

**Comment by SimonLab** [comment]
I think this issue is now finally ready to be reviewed @iteles @nelsonic  see #42

**Comment by nelsonic** [comment]
merged. closing. thanks again @SimonLab 👍
