### ISSUE TITLE
Redis connection not reset if it has been closed

### ISSUE THREAD

**Issue by SimonLab** [dwyl/redis-connection#21]
if we call redis.close() and if we then attempt to reset the connection with ``` require('redis-connection')()``` it won't work because the [redisClient](https://github.com/dwyl/redis-connection/blob/master/index.js) is not undefined.

If we want to not allow the redis connection to be created again (even after ending the connection) we could create a specific function (client.kill() ?)?

**Comment by nelsonic** [comment]
Hmm... good question! Would you mind creating a branch with a *Test* that illustrates this?

**Comment by nelsonic** [comment]
@SimonLab do you still need this? or can you provide a bit more detail? 
I think I *may* have run into the same issue in my tests...
