### ISSUE TITLE
Where is the host URL defined?

### ISSUE THREAD

**Issue by alexdrans** [dwyl/redis-connection#24]
I am brand new to Redis, and I'm interested in using this module, however, I cannot figure out how to point it at my Heroku redis instance. How do I define the host?

**Comment by nelsonic** [comment]
Hi @alexdrans do you already have a heroku redis instance? You should have a url for it. You will need to save that url as an environment variable.

**Comment by alexdrans** [comment]
What's the env variable, or how do I define it?

**Comment by nelsonic** [comment]
@alexdrans good question. 
the answer is here: https://github.com/dwyl/learn-redis#which-redis-as-a-service-heroku-addon
and here: https://github.com/dwyl/learn-environment-variables
let us know if you get stuck. 👍

**Comment by alexdrans** [comment]
You're awesome @nelsonic, thank you for your help. I understand Redis much better after reading those guides. RedisCloud is set up, but I am still having trouble connecting to it. The env variable is defined and is being loaded correctly from env2, but where do I specify the connection URL to redis-connection?

**Comment by nelsonic** [comment]
Let's re-cap the steps:
When you enable a RedisCloud instance for a Heroku App they will give you a URL (*which includes a username and password*). Once you have successfully found that URL and put it in an `.env` file,
all you need to do is:
```js
require('env2')('.env');
var redisClient = require('redis-connection')(); // require & connect
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
});
```
`redis-connection` *expects* the Redis url in `process.env.REDISCLOUD_URL`.

**Comment by alexdrans** [comment]
And it's working! My issue was that I wasn't explicitly declaring the .env file, although printing out process.env.REDISCLOUD_URL was printing the variable, it appears it wasn't being loaded into the module. All is well.

Thank you so much for your help @nelsonic and the rest of dwyl. I'll stick around ;)

**Comment by nelsonic** [comment]
@alexdrans please :star: repos to signal to others on GitHub that you found it *useful*. 👍

**Comment by nelsonic** [comment]
Closing. 👍
