### ISSUE TITLE
Unhandled error event on momentarily loss of connection

### ISSUE THREAD

**Issue by mean4** [dwyl/redis-connection#28]
When I run the following example server (connecting to RedisCloud) I get an unhandled error if the connection to the redis database is lost momentarily. What is the correct way to handle this event? I found that adding som error handling in `redis-connection\index.js` solved the problem, but I have no idea if that is the correct way to handle it?
I replaced:
```
function new_connection () {
  var redis_con = redis.createClient(rc.port, rc.host);
  redis_con.auth(rc.auth);
  return redis_con;
}
```
with:
```
function new_connection () {
  var redis_con = redis.createClient(rc.port, rc.host);
  redis_con.on("error", function (err) {
    console.log("Error " + err);
  });
  redis_con.auth(rc.auth);
  return redis_con;
}
```
in `redis-connection\index.js`.

The setup is as follows:
hapi: v. 14.1.0
redis-connection: v. 5.0.0
node: v. 5.6.0

The server:
```
'use strict';

const Hapi = require('hapi');

var redisClient = require('redis-connection')(); // instantiate redis-connection

redisClient.set('redis', 'working');
redisClient.get('redis', function (rediserror, reply) {
    if(rediserror) {
        console.log(rediserror);
    }
    console.log('redis is ' +reply.toString()); // confirm we can access redis
});

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({
    host: 'localhost',
    port: 8000
});

// Add the route
server.route({
    method: 'GET',
    path:'/hello',
    handler: function (request, reply) {

        return reply('hello world');
    }
});

// Start the server
server.start((err) => {

    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});
```

The unhandled error:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to <<myDatabaseUrl>> read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:546:26)
```

**Comment by nelsonic** [comment]
@mean4 thanks very much for reporting this! under what circumstances are you seeing the drop in connection?

**Comment by mean4** [comment]
@nelsonic, thanks for the reply. The drop in connection is due to unstable internet connection from my internet provider. Hence there is little I can do about it, and it really is just a matter about handling the event properly (I'm quite new to both Node and Redis).

**Comment by des-des** [comment]
@mean4, listening for errors on the redis client object is the right way to go.

However, I think you can listen for these on the return value of redis-connection.

eg.
```js
var redisClient = require('redis-connection')(); // instantiate redis-connection
redisClient.on("error", function (err) {
    console.log("Error " + err);
  });
```
The object that redis-connection is giving you is the same as the one you are editing in the solution you have posted at the top.

The one from this module: https://github.com/NodeRedis/node_redis.

I am not sure how to handle the connection dropped error once you have caught it though ..

**Comment by mean4** [comment]
Thanks @des-des,

Catching the error on the object returned from redis-connection - as you proposed - works just fine.
