### ISSUE TITLE
node_redis: Warning: Redis server does not require a password, but a password was supplied.

### ISSUE THREAD

**Issue by mitchellporter** [dwyl/redis-connection#31]
Posting this here because not sure if this has to do with something `redis-connection` is abstracting away. The following logs to terminal whenever starting up the app:

`node_redis: Warning: Redis server does not require a password, but a password was supplied.`

**Comment by nelsonic** [comment]
@mitchellporter thanks for creating this issue. we see it in our app(s) too but have ignored it because it's a `warning` but let's _fix_ it!

**Comment by mitchellporter** [comment]
@nelsonic thanks for the dwyl invite! I'll start taking a look at this later tonight. Should have a PR submitted for this very soon :)

**Comment by mitchellporter** [comment]
Apologies for the wait on this. Want to make sure I take the time to fix this properly, test, etc. and have been busy getting a project ready for launch. Should be able to handle this within the next few weeks and would appreciate you leaving it for me. Will be a great way to kickoff my dwyl membership ;)

**Comment by bron10** [comment]
Any updates? :|

**Comment by nelsonic** [comment]
Fixed the issue. new version `redis-connection@5.1.0` on NPM. ✅ 
@bron10 thanks for reminding us! and `welcome` to @dwyl! 🎉

**Comment by bron10** [comment]
Thanks for adding me :)
