### ISSUE TITLE
Question about closing connection

### ISSUE THREAD

**Issue by mitchellporter** [dwyl/redis-connection#32]
In the `README`, this is the code example for closing your connection to redis:

```
var redisClient = require('redis-connection')(); // require & connect
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
  redisClient.end();
});
```

Here's an example I came up with called `userController.js` that handles `HTTP` requests to our users endpoint for an API:

```
var redisClient = require('redis-connection')(); // require & connect

function handleGET(req, res) {
// ... doing other stuff up here

// redis code
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
  redisClient.end();
});
}

function handlePOST(req, res) {
// ... doing other stuff up here

// redis code
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
  redisClient.end();
});
}

function handlePUT(req, res) {
// ... doing other stuff up here

// redis code
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
  redisClient.end();
});
}

function handleDELETE(req, res) {
// ... doing other stuff up here

// redis code
redisClient.set('hello', 'world');
redisClient.get('hello', function (err, reply) {
  console.log('hello', reply.toString()); // hello world
  redisClient.end();
});
}
```

For the example above that I shared, would I be using `redis-connection` correctly? I'm fairly certain that you basically just need to call `redisClient.end()` whenever you are done sending a single command to redis.. is that correct? 

The reason I'm asking is because I have similar files in my node API based on the example I showed above, and each controller function accesses redis in its own way issuing various redis commands like `hmset`, `hgetall`, `zadd`, `hincrby`, etc. I wanted to make sure that I'm using `redisClient.end()` correctly.

**Comment by nelsonic** [comment]
@mitchellporter _great_ question!
you are _correct_ if/when you need to _close_ your connection to `redis` just call `redisClient.end()` however, closing the connection _each_ time you use it is "_expensive_". 
The _beauty_ of `redis-connection` is that you don't _need_ to keep opening and closing (ending) the connection.

**Comment by mitchellporter** [comment]
Hey @nelsonic thanks for the fast response! So based on what you said, how do you know when you actually need to call `redisClient.end() `then? How do you decide when to call it and when to not call it?

**Comment by nelsonic** [comment]
@mitchellporter _also_ a _good question_!
I tend to keep the connection to Redis open for the _duration_ of the server's "lifecycle".
(_i.e. seldom close it manually_)

**Comment by mitchellporter** [comment]
Awesome now we're getting somewhere :)

This is from the `README`: 

> An easy way to re-use your single Redis connection (or pair of connections - when using Redis Publish/Subscribe) across multiple files/handlers in your application and close once at the end of your tests.

And then you said:

>I tend to keep the connection to Redis open for the duration of the server's "lifecycle".

So basically `redis-connection` helps in the fact that you can call `require('redis-connection')()` in all of your nodejs app's files and they are all still using the single open connection that was created the first time that `require('redis-connection')()` was called?

So where do you tend to place your `redisClient.end()` then? I'm assuming you listen for a specific `EventEmitter` event from node when the server is going to shutdown and when you receive that event you make sure the registered handler function fires `redisClient.end()`

**Comment by nelsonic** [comment]
@mitchellporter listening to a server end event is our preferred option for closing connections.

If you are using `hapi` for your server, this done _for_ you by: https://github.com/dwyl/hapi-redis-connection which is closed during the `server.on('stop')` event. see: [hapi-redis-connection/index.js#L10](https://github.com/dwyl/hapi-redis-connection/blob/f40a082426a30baa9fc6721655bf0d50c02cdf1a/index.js#L10)

However, there's no "_problem_" with just shutting down the server (node process) which would thus `end` the `redisClient` ...

**Comment by mitchellporter** [comment]
@nelsonic thanks for the clarification. 

>However, there's no "problem" with just shutting down the server (node process) which would thus end the redisClient ...

That's what I figured to seeing as how if the server is going to crash and you somehow miss an event I guess the `redis` connection would be lost/closed anyways.

I'm using `express` for this current project but have been meaning to take a look at `hapi` and it looks like now I have an excuse to.

**Comment by mitchellporter** [comment]
@nelsonic I'm experiencing some weird behavior with my redis instance right now and wanted to get your opinion on the situation. I'm using a free plan on `RedisCloud` right now just for testing, and they have given me a max connection limit of 30. Lately I've been doing more testing and getting email warnings that I've exceeded using 90% of my connections and am very close to reaching the limit.

You mentioned this a couple comments up:

> However, there's no "problem" with just shutting down the server (node process) which would thus end the redisClient ...

Do you think it's possible that somehow the connection is left open when the node server crashes if I don't actually call `redisClient.end()` anywhere? I seem to get the warning emails when I have crashed the node server a few times in a row when testing things. I could be wrong, but it seems like this is when it happens which would mean that somehow the connection is still being kept open...

What node server event do you usually listen for to know when to call `redisClient.end()`? You mentioned `hapi.js` earlier but I'm using `express` for this project. I'm going to test calling `redisClient.end()` on the server end event and see if it makes this problem go away.
