### ISSUE TITLE
Better way to input a url

### ISSUE THREAD

**Issue by SupertigerDev** [dwyl/redis-connection#44]
Can you just make it so we can just do
const redisClient = require('redis-connection')({url: "owo url here"})

I dont wanna use env >~<

**Comment by nelsonic** [comment]
@supertiger1234 "better" is _subjective_. We _prefer_ to keep keys safely out of code.
If you want to do what you are suggesting you can _easily_ do it with the existing module and one extra line of code:
```
process.env.REDIS_URL='redis://127.0.0.1:6379/0'
const redisClient = require('redis-connection')
```
You define the `REDIS_URL` in the environment variable in your code 
and don't actually have to _use_ an `.env` file or set environment variables.
