### ISSUE TITLE
After creating connection all error messages are no longer outputed

### ISSUE THREAD

**Issue by SupertigerDev** [dwyl/redis-connection#46]
After initializing
```
process.env.REDISCLOUD_URL = config.redisURL;
const redisClient = require('redis-connection')();
```
the server no long outputs any errors

**Comment by nelsonic** [comment]
@supertiger1234 are you able to run a set/get request against the Redis store?
(_i.e. is the connection to Redis **working**?_)

**Comment by SupertigerDev** [comment]
Yes it is. and I found out, removing this line from redis-connection fixed the problem. Can you please fix it
```
process.on('uncaughtException', report_error);
```

**Comment by nelsonic** [comment]
@supertiger1234 this is due to Node.js' single thread nature all errors "bubble" up to this point.
We _need_ this line in order to catch _uncaught_ exceptions in the `redis-connection`.
If _your_ application is is throwing _uncaught_ exceptions you should be dealing with them appropriately. 
There is nothing to "fix" here.

**Comment by SupertigerDev** [comment]
Well, user errors could occur and when they do, How can I know how to fix em? This IS something to fix.

**Comment by nelsonic** [comment]
@supertiger1234 the point is that **user errors** generated in your application 
should be caught by _your_ application; they should _never_ reach the `process.on('uncaughtException'`

If your application code is _not_ "catching" errors before this `process.on('uncaughtException'` is hit,
then you are not "handling" the errors appropriately... 
Please see: https://www.joyent.com/node-js/production/design/errors

The **_user_ errors** are not the fault of the `redis-connnection` module.
Therefore it's **_definitely_ not** something to "fix" in _this_ node module. 
Please improve your _own_ code before claiming that there is something to "fix" in ours. 
If you don't _want_ to handle the errors in your application appropriately, consider _not_ using Node.js.

# _Thank You_ 🦄 🌈 ✨

**Comment by SupertigerDev** [comment]
Thanks for your reply but just to let you know, no other npm package has ever done this but okay, thanks I gusss

**Comment by nelsonic** [comment]
@supertiger1234, Trust me, I _feel_ your frustration. 😞 
Not only do other NPM packages do this, it's the _only_ way of preventing a Node.js server from "dying". see: [https://github.com/Unitech/pm2/lib/ProcessContainer.js#L289](https://github.com/Unitech/pm2/blob/38ea71ee3a2b268bf6b3e915ce36cc2b9e93051d/lib/ProcessContainer.js#L289) amongst _many_ others.

![in-god-we-trust-all-others-bring-data](https://user-images.githubusercontent.com/194400/51895476-1d043580-23a2-11e9-852c-24b6589d846d.png)

If you ever want to turn your opinion into a _fact_ by using **`data`**, GitHub Search is your friend:
please see: https://github.com/search?q=process.on%28%27uncaughtException%27&type=Code
![image](https://user-images.githubusercontent.com/194400/51894024-8e41e980-239e-11e9-8010-e9ca83626ece.png)

Exception/Error Handling is one of the _biggest_ reasons why I no longer write Node.js Code. 🚫 
I would _highly_ recommend you to switch to **`Elixir`** while you're still _young_. https://github.com/dwyl/learn-elixir/issues/102 💧
